/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as PassportIndexRouteImport } from './routes/passport.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportIndexRoute = PassportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/passport': typeof PassportRouteWithChildren
  '/passport/': typeof PassportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/passport': typeof PassportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/passport': typeof PassportRouteWithChildren
  '/passport/': typeof PassportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/passport' | '/passport/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/passport'
  id: '__root__' | '/' | '/passport' | '/passport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PassportRoute: typeof PassportRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/': {
      id: '/passport/'
      path: '/'
      fullPath: '/passport/'
      preLoaderRoute: typeof PassportIndexRouteImport
      parentRoute: typeof PassportRoute
    }
  }
}

interface PassportRouteChildren {
  PassportIndexRoute: typeof PassportIndexRoute
}

const PassportRouteChildren: PassportRouteChildren = {
  PassportIndexRoute: PassportIndexRoute,
}

const PassportRouteWithChildren = PassportRoute._addFileChildren(
  PassportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PassportRoute: PassportRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
