/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as EmployeePortalRouteImport } from './routes/employee-portal'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as WebDevelopmentRouteImport } from './routes/web-development'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as PassportIndexRouteImport } from './routes/passport.index'
import { Route as PassportServiceRouteImport } from './routes/passport.$service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePortalRoute = EmployeePortalRouteImport.update({
  id: '/employee-portal',
  path: '/employee-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDevelopmentRoute = WebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportIndexRoute = PassportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassportRoute,
} as any)
const PassportServiceRoute = PassportServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => PassportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/employee-portal': typeof EmployeePortalRoute
  '/passport': typeof PassportRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/web-development': typeof WebDevelopmentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/passport/$service': typeof PassportServiceRoute
  '/blog/': typeof BlogIndexRoute
  '/passport/': typeof PassportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/employee-portal': typeof EmployeePortalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/web-development': typeof WebDevelopmentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/passport/$service': typeof PassportServiceRoute
  '/blog': typeof BlogIndexRoute
  '/passport': typeof PassportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/employee-portal': typeof EmployeePortalRoute
  '/passport': typeof PassportRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/web-development': typeof WebDevelopmentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/passport/$service': typeof PassportServiceRoute
  '/blog/': typeof BlogIndexRoute
  '/passport/': typeof PassportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/book'
    | '/digital-marketing'
    | '/employee-portal'
    | '/passport'
    | '/privacy'
    | '/terms'
    | '/track'
    | '/web-development'
    | '/auth/login'
    | '/auth/signup'
    | '/blog/$slug'
    | '/passport/$service'
    | '/blog/'
    | '/passport/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/book'
    | '/digital-marketing'
    | '/employee-portal'
    | '/privacy'
    | '/terms'
    | '/track'
    | '/web-development'
    | '/auth/login'
    | '/auth/signup'
    | '/blog/$slug'
    | '/passport/$service'
    | '/blog'
    | '/passport'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/book'
    | '/digital-marketing'
    | '/employee-portal'
    | '/passport'
    | '/privacy'
    | '/terms'
    | '/track'
    | '/web-development'
    | '/auth/login'
    | '/auth/signup'
    | '/blog/$slug'
    | '/passport/$service'
    | '/blog/'
    | '/passport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  EmployeePortalRoute: typeof EmployeePortalRoute
  PassportRoute: typeof PassportRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  WebDevelopmentRoute: typeof WebDevelopmentRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-portal': {
      id: '/employee-portal'
      path: '/employee-portal'
      fullPath: '/employee-portal'
      preLoaderRoute: typeof EmployeePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-development': {
      id: '/web-development'
      path: '/web-development'
      fullPath: '/web-development'
      preLoaderRoute: typeof WebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/': {
      id: '/passport/'
      path: '/'
      fullPath: '/passport/'
      preLoaderRoute: typeof PassportIndexRouteImport
      parentRoute: typeof PassportRoute
    }
    '/passport/$service': {
      id: '/passport/$service'
      path: '/$service'
      fullPath: '/passport/$service'
      preLoaderRoute: typeof PassportServiceRouteImport
      parentRoute: typeof PassportRoute
    }
  }
}

interface PassportRouteChildren {
  PassportServiceRoute: typeof PassportServiceRoute
  PassportIndexRoute: typeof PassportIndexRoute
}

const PassportRouteChildren: PassportRouteChildren = {
  PassportServiceRoute: PassportServiceRoute,
  PassportIndexRoute: PassportIndexRoute,
}

const PassportRouteWithChildren = PassportRoute._addFileChildren(
  PassportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  EmployeePortalRoute: EmployeePortalRoute,
  PassportRoute: PassportRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  WebDevelopmentRoute: WebDevelopmentRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
